server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dynamic?useSSL=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    #    schema: classpath:dynamic.sql

upload:
  relativePath: /files/
  realPath: /home/webFile/

logging:
  file:
    name: log/dynamic.log
